# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Post.create(title: 'first post', content: 'Lorem ipsum dolor sit amet consectetur adipiscing elit volutpat scelerisque neque commodo, hac ante condimentum interdum quis vulputate donec urna eros sociis. Magnis class nam cum pharetra habitasse suspendisse quam accumsan integer dis, nullam justo euismod venenatis fermentum felis nulla cubilia. Suscipit dui habitant montes platea vivamus pulvinar lacinia at, iaculis est quis mollis libero fringilla massa orci a, tempor fusce luctus nulla egestas per nullam.', image: 'https://cnnespanol.cnn.com/wp-content/uploads/2019/12/s_64a163f16ecbb099e52f2f8271f73cbbfcfc9034be4d646f7375e4db1ca6f3d7_1573501883482_ap_19001106049831-1.jpg?quality=100&strip=info&w=320&h=240&crop=1')
Post.create(title: 'first post', content: 'Lorem ipsum dolor sit amet consectetur adipiscing elit volutpat scelerisque neque commodo, hac ante condimentum interdum quis vulputate donec urna eros sociis. Magnis class nam cum pharetra habitasse suspendisse quam accumsan integer dis, nullam justo euismod venenatis fermentum felis nulla cubilia. Suscipit dui habitant montes platea vivamus pulvinar lacinia at, iaculis est quis mollis libero fringilla massa orci a, tempor fusce luctus nulla egestas per nullam.', image: 'https://ep01.epimg.net/elpais/imagenes/2019/10/30/album/1572424649_614672_1572453030_noticia_normal.jpg')
Post.create(title: 'first post', content: 'Lorem ipsum dolor sit amet consectetur adipiscing elit volutpat scelerisque neque commodo, hac ante condimentum interdum quis vulputate donec urna eros sociis. Magnis class nam cum pharetra habitasse suspendisse quam accumsan integer dis, nullam justo euismod venenatis fermentum felis nulla cubilia. Suscipit dui habitant montes platea vivamus pulvinar lacinia at, iaculis est quis mollis libero fringilla massa orci a, tempor fusce luctus nulla egestas per nullam.', image: 'https://www.muycomputer.com/wp-content/uploads/2016/07/portada.jpg')